specVersion: '0.2.0'

name: 'subscan-multisig'
version: '0.0.1'
description: ''
repository: ''

schema:
  file: './schema.graphql'

dataSources:
  - kind: substrate/Runtime
    startBlock: 1392130
    mapping:
      file: './dist/index.js'
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
        - handler: handleCall
          kind: substrate/CallHandler

network:
  # Polkadot
  # genesisHash: '0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3'
  # endpoint: wss://rpc.polkadot.io

  # endpoint: wss://kusama.api.onfinality.io/public-ws

  # endpoint: wss://rpc.darwinia.network

  # endpoint: wss://crab-rpc.darwinia.network

  # genesisHash: '0xe4c7d754ef479eaa1f7d3cad9905353211339f1daa5cddee5c289540a7754f86' # pangolin
  genesisHash: '0xf9d24fa9ec4ccb07c966e2feee7b0cfd82c23065b0b556098c6c27b3c66d04f1' # pangolin
  endpoint: wss://pangolin-rpc.darwinia.network/

  chaintypes:
    file: './pangolin_types.yaml'
